//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITService.Classes
{
    using System;
    using System.Collections.Generic;
    
    public partial class Applications
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Applications()
        {
            this.Order = new HashSet<Order>();
        }
    
        public int Id { get; set; }
        public string Articul { get; set; }
        public int IdClient { get; set; }
        public string Device { get; set; }
        public string ModelDevice { get; set; }
        public string Description { get; set; }
        public int IdStatusApplication { get; set; }
        public System.DateTime StartData { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
    
        public virtual StatusApplications StatusApplications { get; set; }
        public virtual Users Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Order { get; set; }
    }
}
